"""Development-only numerical oracle for DeepSeek V4 Flash DSpark.

This package deliberately depends on NumPy, not on the Hebrus runtime.  It is
used to generate and check small fixtures before the same equations are
implemented in the production Metal path.
"""

from .metadata import DSparkMetadata, MetadataError, validate_0731_metadata
from .reference import (
    ConfidenceSchedule,
    DSPARK_RAW_CACHE_WIDTH,
    DSPARK_RAW_CACHE_WINDOW,
    DSPARK_STAGE_COUNT,
    DraftHead,
    HCSplit,
    MarkovDraft,
    RawCacheState,
    SpeculativeSample,
    StageChain,
    StageSetup,
    append_raw_cache,
    conditional_confidence,
    empty_raw_cache,
    finalize_draft_head,
    hc_head,
    hc_post,
    hc_pre,
    hc_split_sinkhorn,
    logical_raw_cache,
    main_project_and_norm,
    markov_greedy_draft,
    markov_sampled_draft,
    markov_step_bias,
    post_layer_hc_mean,
    prefill_raw_cache,
    prepare_stage_zero,
    proposal_raw_cache_view,
    rms_norm,
    run_synthetic_stage_chain,
    speculative_sample_exact,
)

__all__ = [
    "ConfidenceSchedule",
    "DSPARK_RAW_CACHE_WIDTH",
    "DSPARK_RAW_CACHE_WINDOW",
    "DSPARK_STAGE_COUNT",
    "DSparkMetadata",
    "DraftHead",
    "HCSplit",
    "MarkovDraft",
    "MetadataError",
    "RawCacheState",
    "SpeculativeSample",
    "StageChain",
    "StageSetup",
    "append_raw_cache",
    "conditional_confidence",
    "empty_raw_cache",
    "finalize_draft_head",
    "hc_head",
    "hc_post",
    "hc_pre",
    "hc_split_sinkhorn",
    "logical_raw_cache",
    "main_project_and_norm",
    "markov_greedy_draft",
    "markov_sampled_draft",
    "markov_step_bias",
    "post_layer_hc_mean",
    "prefill_raw_cache",
    "prepare_stage_zero",
    "proposal_raw_cache_view",
    "rms_norm",
    "run_synthetic_stage_chain",
    "speculative_sample_exact",
    "validate_0731_metadata",
]
