#!/usr/bin/env python3
"""Generate the Metal lookup tables needed by the Qwen3.6 IQ kernels."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPO_ROOT / "gguf-tools" / "vendor" / "qwen35-iq-ggml-common.h"
DEFAULT_OUTPUT = REPO_ROOT / "metal" / "qwen35_iq_tables.metal.inc"
UPSTREAM_REVISION = "bf2c86ddc0685f580595954056c2e77ebabfab4f"

TABLES = (
    ("iq2xs_grid", "ulong", "ds4_metal_iq2xs_grid", 512, 4),
    ("iq3xxs_grid", "uint", "ds4_metal_iq3xxs_grid", 256, 8),
    ("kvalues_iq4nl", "float", "ds4_metal_kvalues_iq4nl_f", 16, 8),
)

TABLE_BEGIN_RE = re.compile(
    r"^GGML_TABLE_BEGIN\([^,]+,\s*([A-Za-z0-9_]+),\s*(\d+)\)\s*$"
)
INTEGER_RE = re.compile(r"-?0x[0-9A-Fa-f]+|-?\d+")


def parse_tables(source: str) -> dict[str, list[str]]:
    tables: dict[str, list[str]] = {}
    current_name: str | None = None
    current_values: list[str] = []

    for line in source.splitlines():
        stripped = line.strip()
        if current_name is None:
            match = TABLE_BEGIN_RE.match(stripped)
            if match:
                current_name = match.group(1)
                current_values = []
            continue
        if stripped == "GGML_TABLE_END()":
            tables[current_name] = current_values
            current_name = None
            current_values = []
            continue
        current_values.extend(INTEGER_RE.findall(stripped))

    if current_name is not None:
        raise ValueError(f"unterminated table {current_name}")
    return tables


def render_table(
    source_name: str,
    metal_type: str,
    output_name: str,
    expected_count: int,
    values_per_line: int,
    values: list[str],
) -> str:
    if len(values) != expected_count:
        raise ValueError(
            f"{source_name}: expected {expected_count} values, found {len(values)}"
        )
    if metal_type == "float":
        rendered_values = [f"{int(value, 0)}.0f" for value in values]
    else:
        rendered_values = values

    lines = [
        f"static constant {metal_type} {output_name}[{expected_count}] = {{"
    ]
    for offset in range(0, expected_count, values_per_line):
        lines.append("    " + ", ".join(rendered_values[offset : offset + values_per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def render(source: str) -> str:
    parsed = parse_tables(source)
    sections = [
        "// Generated by gguf-tools/generate_qwen35_iq_metal.py; do not edit.",
        "// Input: gguf-tools/vendor/qwen35-iq-ggml-common.h",
        "// Provenance: llama.cpp ggml/src/ggml-common.h",
        f"// Upstream revision: {UPSTREAM_REVISION}",
        "",
    ]
    for spec in TABLES:
        source_name = spec[0]
        if source_name not in parsed:
            raise ValueError(f"missing table {source_name}")
        sections.append(render_table(*spec, parsed[source_name]))
        sections.append("")
    return "\n".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render(args.input.read_text(encoding="utf-8"))
    if args.check:
        if not args.output.exists():
            raise SystemExit(f"missing generated file: {args.output}")
        actual = args.output.read_text(encoding="utf-8")
        if actual != expected:
            raise SystemExit(
                f"{args.output} is stale; run {Path(__file__).name}"
            )
        return 0

    args.output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
